### PR TITLE
Timejs temp patch

### LINKED ISSUE #173: Remove confirmation on unload events
Whenever you try to try to edit or leave a room, you see a javascript confirmation popup:

djangole grooming 2017-10-20 pokrex 2017-10-19 10-24-00

This is quite annoying because it interrupts user flow.

I propose removing it.

### PR DESCRIPTION
**Pull request by hlcfan**
Fix #173

### CODE REVIEW

**Comment by sloria** [comment]
Thanks for this fix!

**Comment by hlcfan** [comment]
@sloria No problem. Timeme.js isn't suitable for the situation, I'll try to remove it and have new way to handle timing in next PR. Do you think "timing(grooming duration)" is an useful metric?

**Comment by sloria** [comment]
@hlcfan My team doesn't track grooming duration, so it isn't useful for us. Personally, I don't think it's a necessary feature. For those that need it, timing can be done more accurately outside of pokrex.

**Comment by hlcfan** [comment]
Makes sense, will remove it then. Thanks!

**Pull request merged**
