### PR TITLE
Disable user vote after cards flipped

### PR DESCRIPTION
**Pull request by hlcfan**
> If people change their vote in response to others without discussion, we can’t improve collaboration as much.

👆

### CODE REVIEW

**Comment by hlcfan** [comment]
@sloria Hi man, what's your thought on this?

**Comment by sloria** [comment]
Not sure it's a good idea. 

My team discusses a ticket before *and* after the cards are flipped. After the cards are flipped, everyone is given a chance to speak for their estimate. After that, people may change their vote. This would seem to break that.

**Comment by hlcfan** [comment]
I didn't express the purpose of this PR clearly 😅

After cards are flipped, participants cannot change their votes, after discussion done, moderator can clear all the votes, then everyone can vote again.

**Comment by sloria** [comment]
I see. My team hasn't done the "re-voting" process you described. I see the potential value in it, so maybe I'll see how it goes at our next grooming meeting.

I still lean towards the "we're all adults" policy here. If you don't want your team to change their votes, then decide that as a team, but the tool doesn't need to impose that restriction.

**Comment by hlcfan** [comment]
Yea, make sense! It's what I was thinking as well at the beginning. Dig the **"we're all adults" policy**. Will keep this PR for some time, so that i can talk with other teams. Thanks for your opinion.

**Pull request closed without merging**
